### ISSUE TITLE
RSS feed not working

### ISSUE THREAD

**Issue by andrewwippler** [pastorryanhayden/blog#1]
Somewhere there is an RSS feed option in your blog. Unfortunately for me `/feed.xml` returns a 404.

Just looking at options to ditch social media. One was to subscribe to RSS feeds (like, before social media). I am thinking about creating a program that generates a daily newspaper for me in PDF form from RSS that I can read on my kindle/remarkable. That way I only have to look at it once a day/week/month.

**Comment by pastorryanhayden** [comment]
Just seeing this. I can add an RSS feed.

**Comment by pastorryanhayden** [comment]
This should be fixed with the last commit.

**Comment by andrewwippler** [comment]
Sorry to beat a dead horse, but the rss feed is not working: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fpastorryanhayden.com%2Ffeed
